production:
    first_thing:
      - source: /config/cloud/cloud66/scripts/1_install.sh
        destination: /tmp/install.sh
        target: rails
        apply_during: build_only
        run_on: all_servers
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/scripts/2_env_var_perms.sh
        destination: /tmp/env_var_perms.sh
        target: rails
        apply_during: all
        run_on: all_servers
        execute: true
        sudo: true
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        parse: false
        run_on: all_servers
      - source: /config/cloud/cloud66/files/resque.yml
        destination: <%= ENV['STACK_PATH'] %>/config/resque.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab_config.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab_config.yml
        target: rails
        parse: true
        run_on: all_servers
      - source: /config/cloud/cloud66/files/production.rb
        destination: <%= ENV['STACK_PATH'] %>/config/environments/production.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/smtp_settings.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/smtp_settings.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/rack_attack.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/rack_attack.rb
        target: rails
        run_on: all_servers
    last_thing:
      - source: /config/cloud/cloud66/scripts/3_add_user.sh
        destination: /tmp/add_user.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: true
      - source: /config/cloud/cloud66/scripts/4_permissions.sh
        destination: /tmp/permissions.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/5_gitlab_shell.sh
        destination: /tmp/gitlab_shell.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/6_logging.sh
        destination: /tmp/logging.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/7_seed.sh
        destination: /tmp/seed.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/files/gitlab_shell_update
        destination: /home/git/gitlab-shell/hooks/update
        target: rails
        parse: false
        run_on: all_servers
staging:
    first_thing:
      - source: /config/cloud/cloud66/scripts/1_install.sh
        destination: /tmp/install.sh
        target: rails
        apply_during: build_only
        run_on: all_servers
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/scripts/2_env_var_perms.sh
        destination: /tmp/env_var_perms.sh
        target: rails
        apply_during: all
        run_on: all_servers
        execute: true
        sudo: true
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        parse: false
        run_on: all_servers
      - source: /config/cloud/cloud66/files/resque.yml
        destination: <%= ENV['STACK_PATH'] %>/config/resque.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab_config.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab_config.yml
        target: rails
        parse: true
        run_on: all_servers
      - source: /config/cloud/cloud66/files/production.rb
        destination: <%= ENV['STACK_PATH'] %>/config/environments/production.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/smtp_settings.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/smtp_settings.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/rack_attack.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/rack_attack.rb
        target: rails
        run_on: all_servers
    last_thing:
      - source: /config/cloud/cloud66/scripts/3_add_user.sh
        destination: /tmp/add_user.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: true
      - source: /config/cloud/cloud66/scripts/4_permissions.sh
        destination: /tmp/permissions.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/5_gitlab_shell.sh
        destination: /tmp/gitlab_shell.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/6_logging.sh
        destination: /tmp/logging.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/7_seed.sh
        destination: /tmp/seed.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/files/gitlab_shell_update
        destination: /home/git/gitlab-shell/hooks/update
        target: rails
        parse: false
        run_on: all_servers
development:
    first_thing:
      - source: /config/cloud/cloud66/scripts/1_install.sh
        destination: /tmp/install.sh
        target: rails
        apply_during: build_only
        run_on: all_servers
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/scripts/2_env_var_perms.sh
        destination: /tmp/env_var_perms.sh
        target: rails
        apply_during: all
        run_on: all_servers
        execute: true
        sudo: true
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        parse: false
        run_on: all_servers
      - source: /config/cloud/cloud66/files/resque.yml
        destination: <%= ENV['STACK_PATH'] %>/config/resque.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/gitlab_config.yml
        destination: <%= ENV['STACK_PATH'] %>/config/gitlab_config.yml
        target: rails
        parse: true
        run_on: all_servers
      - source: /config/cloud/cloud66/files/production.rb
        destination: <%= ENV['STACK_PATH'] %>/config/environments/production.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/smtp_settings.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/smtp_settings.rb
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/rack_attack.rb
        destination: <%= ENV['STACK_PATH'] %>/config/initializers/rack_attack.rb
        target: rails
        run_on: all_servers
    last_thing:
      - source: /config/cloud/cloud66/scripts/3_add_user.sh
        destination: /tmp/add_user.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: true
      - source: /config/cloud/cloud66/scripts/4_permissions.sh
        destination: /tmp/permissions.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/5_gitlab_shell.sh
        destination: /tmp/gitlab_shell.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/6_logging.sh
        destination: /tmp/logging.sh
        target: rails
        apply_during: build_only
        execute: true
        run_on: all_servers
        sudo: false
      - source: /config/cloud/cloud66/scripts/7_seed.sh
        destination: /tmp/seed.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/scripts/8_dev_seed.sh
        destination: /tmp/dev_seed.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
      - source: /config/cloud/cloud66/files/gitlab_shell_update
        destination: /home/git/gitlab-shell/hooks/update
        target: rails
        parse: false
        run_on: all_servers